name: Build and Push Docker image to Docker Hub

on: push
   

jobs:

  push_to_registory:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf77
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Metadata (tags, labels) for Docker
      uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
      with:  
        images: my-docker-hub-namespace/my-docker-hub-repository
  
    - name: Build and push Docker images
      uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
      with:
        context: .
        push: true
        tags: bdahiya2007/java-app:latest
